In [2]:
# Importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
caminho2 = 'C:\\Users\\CRISTINA RAMOS\\Desktop\\Anaconda Projects\\dfdb-final\\datasets\\or\\compras(3).xlsx'

## 4 - Desafio enunciado 2

In [3]:
produtos = pd.read_html('https://profleandrolessa.wordpress.com/exercicio-de-coleta-de-dados/', decimal=',', thousands ='.', header = 0)[0]
produtos

,cod_produto,nome_produto,cod_classe_produto,classe_produto,valor
0,1000,Sabão em pó,1,Produtos de Limpeza,9.90
1,1001,Amaciante,1,Produtos de Limpeza,22.00
2,1002,Detergente,1,Produtos de Limpeza,1.99
3,1003,Água sanitária,1,Produtos de Limpeza,12.00
4,1004,Esponja de aço,1,Produtos de Limpeza,4.00
...,...,...,...,...,...
82,1082,Peixe,5,Carnes e Frios,29.99
83,1083,Frango,5,Carnes e Frios,1.99
84,1084,Carne vermelha,5,Carnes e Frios,56.99
85,1085,Carne seca,5,Carnes e Frios,64.99
86,1086,Salsicha,5,Carnes e Frios,15.90